version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
  - dependency-name: eslint-config-airbnb-typescript
    versions:
    - 12.3.1
  - dependency-name: class-transformer
    versions:
    - 0.3.2
  - dependency-name: "@prisma/cli"
    versions:
    - 2.15.0
    - 2.16.0
    - 2.16.1
