name: Integration tests

on:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - package.json
      - package-lock.json
      - prisma/**
      - src/**
      - tsconfig.json
      - jest.config.js
      - .github/workflows/integration-tests.yml

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Launch database
        run: source .envrc; npm run dev:db

      - name: Launch redis
        run: source .envrc; npm run dev:redis

      - name: Run integration tests
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          changes-only: true
          test-command: source .envrc; npm run integration
