name: Documentation

on:
  push:
    branches:
      - dev

jobs:
  documentation:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup flutter environment
        uses: subosito/flutter-action@v1

      - name: Install dartdoc
        run: flutter pub global activate dartdoc

      - name: Generate documentation
        run: flutter pub global run dartdoc

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: doc/api
