name: Integration tests

on:
  push:
    branches-ignore:
     - gh-pages
    paths:
      - package.json
      - package-lock.json
      - prisma/**
      - src/**
      - tsconfig.json
      - .github/workflows/integration-tests.yml

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm install

    - name: Launch database
      run: source .envrc; npm run dev:db

    - name: Run integration tests
      run: source .envrc; npm run integration
