name: Merge greeting

on:
  pull_request:
    types: [closed]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch gifs
        run: curl "https://api.giphy.com/v1/gifs/search?q=congratulation&api_key=YRosHbxsmDAZ6JI7xZ0M5J4EqpMb3xKj&limit=100" > .gifs

      - name: Select random gif and comment issue
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            try {
              const gifs = JSON.parse(fs.readFileSync('.gifs').toString());
              core.info(`Fetched ${gifs.data.length} gifs`);
          
              const randomIndex = Math.floor(Math.random() * (gifs.data.length - 1));
              core.info(`Selected gif number ${randomIndex}`);

              const gif = gifs.data[randomIndex];
              const url = gif.images.original.url
                          
              core.info(`Url : ${url}`);
            
              const { owner, repo } = context.repo;
              const { data } = github.rest.issues.createComment({
                owner,
                repo,
                issue_number: context.issue.number,
                body: `![Congratulations](${url})`,
              });
            } catch (err) {
              core.setFailed(err.message);
            }
