name: Merge greeting

on:
  pull_request:
    types: [closed]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch greetings gif
        id: fetch-gifs
        run: curl "https://api.giphy.com/v1/gifs/search?q=congratulation&api_key=YRosHbxsmDAZ6JI7xZ0M5J4EqpMb3xKj&limit=100" > .gifs

      - name: Select random gif
        uses: actions/github-script@v5
        id: select-gif
        with:
          script: |
            const fs = require('fs');
            try {
              const gifs = JSON.parse(fs.readFileSync('.gifs').toString());
          
              const gif = gifs.data[Math.floor(Math.random() * 99)];
              const url = gif.images.original.url
                          
              core.info(`Url : ${url}`);
            
              const { owner, repo } = context.repo;
              const { data } = github.rest.issues.createComment({
                owner,
                repo,
                issue_number: context.issue.number,
                body: '![Congratulations](${{ steps.select-gif.outputs.url }})',
              });
            } catch (err) {
              core.setFailed(err.message);
            }
