name: Merge greeting

on:
  pull_request:
    types: [closed]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: '![Congratulations](https://github.com/LeChatErrant/API-template/blob/master/.github/assets/congratulation.gif?raw=true)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
