name: Publish

on:
  push:
    branches:
    - dev       # internal
    - staging   # alpha
    - master    # production

jobs:
  build-android:
    runs-on: self-hosted

    env:
      ANDROID_COMPILE_SDK: "28"
      ANDROID_BUILD_TOOLS: "29.0.2"
      ANDROID_SDK_TOOLS: "4333796"

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup java environment
      uses: actions/setup-java@v1
      with:
        java-version: '8.x'

    - name: Cache Android SDK folder
      uses: actions/cache@v1
      with:
        path: android-sdk-linux
        key: ${{ runner.OS }}-android-${{ env.ANDROID_SDK_TOOLS }}

    - name: Install Android SDK
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
        unzip -q -d android-sdk-linux -o android-sdk.zip >/dev/null
        echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
        echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
        echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
        set +o pipefail
        yes | android-sdk-linux/tools/bin/sdkmanager --licenses >/dev/null
        set -o pipefail

    - name: Setup flutter environment
      uses: subosito/flutter-action@v1

    - name: Cache Flutter build folder
      uses: actions/cache@v1
      with:
        path: build
        key: ${{ runner.OS }}-build-${{ hashFiles('**/pubspec.yaml') }}

    - name: Retreive Flutter packages
      run: flutter pub get

    - name: Generate build number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}

    - name: Setup build secret
      run: |
        echo "${{ secrets.ANDROID_APP_KAION_KEY_JKS }}" | base64 --decode > android/app/kaion-key.jks
        echo "${{ secrets.ANDROID_KEY_PROPRIETIES }}" | base64 --decode > android/key.properties
        echo "${{ secrets.ANDROID_SERVICE_ACCOUNT_KEY }}" | base64 --decode > android/service-account.json

    - name: Build an Android bundle
      run: |
        export ANDROID_SDK_ROOT=$PWD/android-sdk-linux
        flutter build appbundle --build-number=$BUILD_NUMBER

    - name: Deploy production artefact
      if: github.ref == 'refs/heads/master'
      uses: maierj/fastlane-action@v0.10.0
      with:
        lane: 'deploy'
        options: '{"track": "production"}'
        subdirectory: 'android'

    - name: Deploy alpha artefact
      if: github.ref == 'refs/heads/staging'
      uses: maierj/fastlane-action@v0.10.0
      with:
        lane: 'deploy'
        options: '{"track": "alpha"}'
        subdirectory: 'android'

    - name: Deploy internal artefact
      if: github.ref == 'refs/heads/dev'
      uses: maierj/fastlane-action@v0.10.0
      with:
        lane: 'deploy'
        options: '{"track": "internal"}'
        subdirectory: 'android'

  # build-ios:
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: subosito/flutter-action@v1

  #   - name: Cache Flutter build folder
  #     uses: actions/cache@v1
  #     with:
  #       path: build
  #       key: ${{ runner.OS }}-build-${{ hashFiles('**/pubspec.yaml') }}

  #   - name: Retreive Flutter packages
  #     run: flutter pub get

  #   - name: Build an iOS bundle
  #     run: flutter build ios
